databases:
  - name: story-vape-db
    plan: free
    postgresMajorVersion: "15"

services:
  - type: web
    name: story-vape
    runtime: docker
    dockerfilePath: ./Dockerfile
    plan: free
    envVars:
      - key: APP_KEY
        sync: false
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: "false"
      - key: APP_URL
        value: https://story-vape.onrender.com
      - key: LOG_LEVEL
        value: info
      - key: LOG_CHANNEL
        value: stderr
      - key: DB_CONNECTION
        value: pgsql
      - key: DB_HOST
        fromDatabase:
          name: story-vape-db
          property: host
      - key: DB_PORT
        fromDatabase:
          name: story-vape-db
          property: port
      - key: DB_DATABASE
        fromDatabase:
          name: story-vape-db
          property: database
      - key: DB_USERNAME
        fromDatabase:
          name: story-vape-db
          property: user
      - key: DB_PASSWORD
        fromDatabase:
          name: story-vape-db
          property: password
      - key: SESSION_DRIVER
        value: database
      - key: CACHE_STORE
        value: database
      - key: QUEUE_CONNECTION
        value: database
